addons:
    apt:
        packages:
            - lmodern
            - texlive-font-utils
            - texlive-fonts-recommended
            - texlive-latex-base
            - texlive-latex-extra
            - texlive-xetex
            - xzdec
script:
    - ./build
