#!/bin/bash

set -e

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BUILD_DIR="${ROOT_DIR}/out"

# Ensure the buil directory exists
mkdir -p "${BUILD_DIR}"

(
    cd "${ROOT_DIR}/src"

    xelatex \
        -output-directory="${BUILD_DIR}" \
        -halt-on-error \
        -interaction=nonstopmode \
        main
)