#!/bin/bash

set -e

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BUILD_DIR="${ROOT_DIR}/out"

s3_contents="${BUILD_DIR}/s3-root"

# Ensure the build directory exists
mkdir -p "${BUILD_DIR}"

(
    cd "${ROOT_DIR}/src"

    xelatex \
        -output-directory="${BUILD_DIR}" \
        -halt-on-error \
        -interaction=nonstopmode \
        main
)

rm -rf "${s3_contents}"
mkdir -p "${s3_contents}"

cp "${BUILD_DIR}/main.pdf" "${s3_contents}/Dustin.Toff.Resume.pdf"
cp -r "${ROOT_DIR}/html-src/." "${s3_contents}"
