AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  DeploymentContentVersion:
    Type: String
    Description: Hash of the source files
Resources:
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: resume.dustintoff.com
  ResumeDustinToffComBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: resume.dustintoff.com
  ResumeDustinToffComBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeDustinToffComBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join ["", [!GetAtt ResumeDustinToffComBucket.Arn, "/*"]]
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
  S3UploadLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      # This can be npm installed or downloaded as a GitHub release artifact
      ContentUri: out/s3-upload-custom-resource-lambda-layer.zip
  S3UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Layers: [!Ref S3UploadLambdaLayer]
      CodeUri: out/s3-root
      Handler:
        s3-upload-custom-resource.handler # This is fixed and references a file provided by
        # this project and available in the Lambda layer.
      Runtime: nodejs14.x
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ResumeDustinToffComBucket
  UploadToBucket:
    Type: Custom::UploadFilesToS3
    Properties:
      ServiceToken: !GetAtt S3UploadLambda.Arn
      BucketName: !Ref ResumeDustinToffComBucket
      ContentVersion: !Ref DeploymentContentVersion
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt ResumeDustinToffComBucket.DomainName
            Id: S3
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [
                  "",
                  [
                    "origin-access-identity/cloudfront/",
                    !Ref CloudFrontOriginAccessIdentity,
                  ],
                ]
        Enabled: true
        DefaultRootObject: "index.html"
        Aliases:
          - resume.dustintoff.com
        DefaultCacheBehavior:
          TargetOriginId: S3
          SmoothStreaming: false
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref ResumeDustinToffComCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
  DomainName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1ER5K5Q0HJR06 # dustintoff.com
      Name: resume.dustintoff.com
      Type: A
      AliasTarget:
        # Global CloudFront Hosted Zone per
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  ResumeDustinToffComCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: resume.dustintoff.com
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: dustintoff.com
          HostedZoneId: Z1ER5K5Q0HJR06
