#!/bin/bash -ex

export AWS_DEFAULT_REGION=us-east-1

lambda_layer_version='v1.0.3'
wget \
        "https://github.com/quittle/s3-upload-custom-resource-lambda-layer/releases/download/${lambda_layer_version}/layer.zip" \
        -O 'out/s3-upload-custom-resource-lambda-layer.zip'

generated_template="out/generated-cloudformation.yml"

aws cloudformation package \
        --template-file "cloudformation.yml" \
        --s3-bucket sam-915290536872 \
        --output-template-file "${generated_template}" \
        --use-json

code_uri="$(jq '.Resources.S3UploadLambda.Properties.CodeUri' "${generated_template}" --raw-output)"

aws cloudformation deploy \
        --template-file "${generated_template}" \
        --stack-name resume-dustintoff-com \
        --capabilities CAPABILITY_IAM \
        --parameter-overrides "DeploymentContentVersion=${code_uri}" \
        --no-fail-on-empty-changeset
