#!/bin/bash -e

CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function aspell_check() {
    aspell \
        --mode=tex \
        --lang=en_US \
        --add-extra-dicts="${CUR_DIR}/aspell-whitelist.txt" \
        list
}

function hunspell_check() {
    hunspell \
        -d en_US \
        -p "${CUR_DIR}/hunspell-whitelist.dic" \
        -l
}

for checker in aspell_check hunspell_check; do
    invalid_words="$( \
        pdftotext 'out/main.pdf' - | \
        eval "$checker" | \
        sort | \
        uniq
    )"

    if [ -n "${invalid_words}" ]; then
        echo "Invalid words found by $checker"
        echo "-------------------"
        echo "${invalid_words}"
        exit 1
    fi
done

