#!/bin/bash

function try_curl() {
    url="$1"

    # Ignore telephone links which won't resolve
    if [[ "${url}" =~ tel:\+?[0-9][0-9\-]+[0-9] ]]; then
        return 0
    fi

    http_code="$(curl \
        --silent \
        --location \
        --write-out '%{http_code}' \
        --output /dev/null \
        "${url}")"

    if [ "${http_code}" != 200 ]; then
        http_code="$(curl \
            --silent \
            --location \
            --write-out '%{http_code}' \
            --output /dev/null \
            --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36' \
            "${url}")"

        if [ "${http_code}" != 200 ]; then
            echo "Failed to load url! ${url}"
            exit 1
        fi
    fi
}

pdfx --json out/main.pdf |
    python -c "import json; import sys; print('\n'.join(json.load(sys.stdin)['references']['url']))" |
    while read url; do
        try_curl "$url"
    done
